// Colección: CHAKRAS — 7 NFTs, 1 temporada
// Julio 2026 — Primera temporada NFT Studio Om Domo

import type { Collection } from "./index";

export const CHAKRAS_COLLECTION: Collection = {
  id: "chakras",
  name: "Chakras",
  nameEs: "Chakras",
  description: "The 7 energy centers of the subtle body — from root to crown consciousness.",
  emoji: "🔴",
  totalNFTs: 7,
  totalSeasons: 1,
  artStyle: "Mandala radial con geometría sagrada, colores vibrantes por chakra, fondo negro profundo, destellos de luz dorada",
  replicateModel: "stability-ai/sdxl",
  basePrompt: "sacred mandala art, spiritual energy center, divine geometry, glowing light, dark background, intricate patterns, om domo nft collection, high quality digital art, 1:1 ratio",
  colorPalette: ["#FF0000", "#FF7F00", "#FFFF00", "#00FF00", "#0000FF", "#4B0082", "#8B00FF"],
  status: "upcoming",
  contractTokenIdRange: [20, 26], // tokenIds 20-26 en el contrato NFT

  seasons: [
    {
      seasonNumber: 1,
      totalSeasons: 1,
      scheduledMonth: "2026-09",
      status: "upcoming",
      nfts: [
        {
          id: "chakra-muladhara",
          name: "Muladhara",
          nameEs: "Chakra Raíz",
          description: "The root chakra — foundation, survival, earth connection. 396 Hz.",
          emoji: "🔴",
          rarityTier: "standard",
          attributes: {
            element: "Tierra",
            frequency: "396 Hz",
            color: "Rojo",
            location: "Base de la columna",
            mantra: "LAM",
            petals: 4,
          },
          promptHints: [
            "red mandala",
            "root chakra muladhara",
            "earth element",
            "four petals lotus",
            "crimson red glowing energy",
            "grounding sacred geometry",
          ],
        },
        {
          id: "chakra-svadhisthana",
          name: "Svadhisthana",
          nameEs: "Chakra Sacral",
          description: "The sacral chakra — creativity, pleasure, fluidity. 417 Hz.",
          emoji: "🟠",
          rarityTier: "standard",
          attributes: {
            element: "Agua",
            frequency: "417 Hz",
            color: "Naranja",
            location: "Bajo abdomen",
            mantra: "VAM",
            petals: 6,
          },
          promptHints: [
            "orange mandala",
            "sacral chakra svadhisthana",
            "water element fluid",
            "six petals lotus",
            "orange glowing energy creative",
            "flowing sacred geometry",
          ],
        },
        {
          id: "chakra-manipura",
          name: "Manipura",
          nameEs: "Plexo Solar",
          description: "The solar plexus — personal power, will, transformation. 528 Hz.",
          emoji: "🟡",
          rarityTier: "standard",
          attributes: {
            element: "Fuego",
            frequency: "528 Hz",
            color: "Amarillo",
            location: "Plexo solar",
            mantra: "RAM",
            petals: 10,
          },
          promptHints: [
            "yellow golden mandala",
            "solar plexus chakra manipura",
            "fire element sun",
            "ten petals lotus",
            "bright yellow glowing power",
            "radiant solar sacred geometry",
          ],
        },
        {
          id: "chakra-anahata",
          name: "Anahata",
          nameEs: "Chakra del Corazón",
          description: "The heart chakra — unconditional love, compassion, harmony. 639 Hz.",
          emoji: "💚",
          rarityTier: "rare",  // el corazón es más raro — edición 33 unidades
          attributes: {
            element: "Aire",
            frequency: "639 Hz",
            color: "Verde",
            location: "Centro del pecho",
            mantra: "YAM",
            petals: 12,
          },
          promptHints: [
            "green mandala heart",
            "heart chakra anahata",
            "air element",
            "twelve petals lotus",
            "emerald green glowing love",
            "compassion sacred geometry star",
          ],
        },
        {
          id: "chakra-vishuddha",
          name: "Vishuddha",
          nameEs: "Chakra de la Garganta",
          description: "The throat chakra — communication, truth, expression. 741 Hz.",
          emoji: "🔵",
          rarityTier: "standard",
          attributes: {
            element: "Éter",
            frequency: "741 Hz",
            color: "Azul",
            location: "Garganta",
            mantra: "HAM",
            petals: 16,
          },
          promptHints: [
            "blue mandala throat",
            "vishuddha chakra",
            "ether element sound",
            "sixteen petals lotus",
            "sky blue glowing voice",
            "communication sacred geometry",
          ],
        },
        {
          id: "chakra-ajna",
          name: "Ajna",
          nameEs: "Tercer Ojo",
          description: "The third eye — intuition, insight, inner vision. 852 Hz.",
          emoji: "🔮",
          rarityTier: "rare",
          attributes: {
            element: "Luz",
            frequency: "852 Hz",
            color: "Índigo",
            location: "Entre las cejas",
            mantra: "OM",
            petals: 2,
          },
          promptHints: [
            "indigo mandala eye",
            "ajna third eye chakra",
            "light element intuition",
            "two petals lotus eye",
            "deep indigo glowing vision",
            "sacred eye geometry cosmic",
          ],
        },
        {
          id: "chakra-sahasrara",
          name: "Sahasrara",
          nameEs: "Chakra de la Corona",
          description: "The crown chakra — pure consciousness, divine connection. 963 Hz.",
          emoji: "👑",
          rarityTier: "legendary", // edición 11 unidades — la más rara
          attributes: {
            element: "Conciencia",
            frequency: "963 Hz",
            color: "Violeta/Blanco",
            location: "Corona de la cabeza",
            mantra: "AH",
            petals: 1000,
          },
          promptHints: [
            "violet white mandala crown",
            "sahasrara thousand petals lotus",
            "pure consciousness divine",
            "violet gold white glowing",
            "crown chakra cosmic universe",
            "enlightenment sacred geometry radiant",
          ],
        },
      ],
    },
  ],
};
