// Colección: PLANTAS MAESTRAS — 13 NFTs, 2 temporadas
// Enfoque: botánica ancestral, medicina tradicional, respeto ceremonial.
// NO promover uso recreativo — enmarcado como sabiduría indígena + científica.
import type { Collection } from "./index";

export const SACRED_PLANTS_COLLECTION: Collection = {
  id: "sacred-plants",
  name: "Sacred Plants",
  nameEs: "Plantas Maestras",
  description: "Ancient botanical wisdom — the plant teachers that have guided human consciousness for millennia.",
  emoji: "🌿",
  totalNFTs: 13,
  totalSeasons: 2,
  artStyle: "Ilustración botánica sagrada, mezcla de arte científico detallado y geometría sagrada luminosa, fondo negro profundo, colores vibrantes naturales de cada planta, estilo enciclopedia ancestral + arte digital místico",
  replicateModel: "black-forest-labs/flux-1.1-pro",
  basePrompt: "sacred plant botanical illustration, detailed scientific art meets sacred geometry, deep black background, vibrant natural plant colors, ancestral encyclopedia meets mystic digital art, ceremonial plant medicine, om domo nft, 1:1 ratio",
  colorPalette: ["#228B22", "#8B4513", "#9333EA", "#FFD700", "#00CED1"],
  status: "upcoming",
  contractTokenIdRange: [149, 161],
  seasons: [
    {
      seasonNumber: 1, totalSeasons: 2, scheduledMonth: "2028-02", status: "upcoming",
      nfts: [
        {
          id: "plant-ayahuasca",
          name: "Ayahuasca",
          nameEs: "Ayahuasca — La Liana del Alma",
          description: "The vine of the soul — Banisteriopsis caapi + Psychotria viridis. Used by Amazonian shamans for millennia. The great teacher.",
          emoji: "🐍",
          rarityTier: "legendary",
          attributes: { origin: "Amazonas", type: "Enteógeno ceremonial", compounds: "Harminas + DMT", tradition: "Amazónica" },
          promptHints: ["ayahuasca vine botanical sacred", "banisteriopsis caapi spiral vines", "amazon shaman plant teacher", "vine soul serpent energy"],
        },
        {
          id: "plant-peyote",
          name: "Peyote",
          nameEs: "Peyote — El Abuelo",
          description: "Grandfather Peyote — Lophophora williamsii. Sacred cactus of the Huichol people. Used ceremonially for 5,000+ years.",
          emoji: "🌵",
          rarityTier: "legendary",
          attributes: { origin: "México / Norteamérica", type: "Enteógeno ceremonial", tradition: "Huichol / NAC", compounds: "Mescalina" },
          promptHints: ["peyote cactus sacred huichol art", "lophophora williamsii ceremonial", "grandfather medicine wheel", "peyote buttons rainbow patterns"],
        },
        {
          id: "plant-psilocybe",
          name: "Psilocybe",
          nameEs: "Psilocybe — Los Hongos Sagrados",
          description: "Sacred mushrooms — Psilocybe cubensis. Used by Mazatec curanderas for healing ceremonies. 'The children' (los niños santos).",
          emoji: "🍄",
          rarityTier: "rare",
          attributes: { origin: "Global (México, Asia, Europa)", type: "Enteógeno ceremonial", compounds: "Psilocibina + Psilocina", tradition: "Mazateca / Azteca" },
          promptHints: ["psilocybe mushroom sacred geometry glow", "mazatec healing mushroom art", "sacred mushroom bioluminescent", "fungi mycelium network sacred"],
        },
        {
          id: "plant-iboga",
          name: "Iboga",
          nameEs: "Iboga — El Gran Iniciador",
          description: "Tabernanthe iboga — the great initiator. Sacred root of the Bwiti tradition in Central Africa. Confronts the deepest shadows.",
          emoji: "🌳",
          rarityTier: "legendary",
          attributes: { origin: "África Central (Gabón)", type: "Enteógeno iniciático", compounds: "Ibogaína", tradition: "Bwiti" },
          promptHints: ["iboga root sacred africa bwiti", "tabernanthe iboga botanical art", "african initiation root medicine", "iboga forest darkness light"],
        },
        {
          id: "plant-san-pedro",
          name: "San Pedro",
          nameEs: "San Pedro — El Maestro del Día",
          description: "Echinopsis pachanoi — the master of the day. Andean cactus used for 3,000 years. Teaches the medicine of the light.",
          emoji: "☀️",
          rarityTier: "rare",
          attributes: { origin: "Andes (Perú, Ecuador)", type: "Enteógeno ceremonial", compounds: "Mescalina", tradition: "Andina / Chamanismo" },
          promptHints: ["san pedro cactus andean sacred", "echinopsis pachanoi columnar cactus art", "andean ceremony sunlight cactus", "day medicine cactus golden"],
        },
        {
          id: "plant-kanna",
          name: "Kanna",
          nameEs: "Kanna — El Corazón del Khoisan",
          description: "Sceletium tortuosum — used by the San people of South Africa for centuries. Melts fear, opens the heart, connects community.",
          emoji: "💛",
          rarityTier: "standard",
          attributes: { origin: "Sudáfrica", type: "Planta adaptógena / enteógeno suave", compounds: "Mesembrina", tradition: "San / Khoikhoi" },
          promptHints: ["kanna sceletium sacred san people", "south africa healing plant art", "heart opener khoisan botanical", "sceletium tortuosum golden flowers"],
        },
        {
          id: "plant-salvia",
          name: "Salvia Divinorum",
          nameEs: "Salvia Divinorum — La Profetisa",
          description: "The prophetess — Salvia divinorum. Used by Mazatec curanderas for divination and healing. Sharpest, most immediate plant teacher.",
          emoji: "🔮",
          rarityTier: "rare",
          attributes: { origin: "Oaxaca, México", type: "Enteógeno visionario", compounds: "Salvinorina A", tradition: "Mazateca" },
          promptHints: ["salvia divinorum mazatec sacred plant", "mint family purple divination plant", "prophetess sage botanical visions", "salvia leaves mystical glow"],
        },
      ],
    },
    {
      seasonNumber: 2, totalSeasons: 2, scheduledMonth: "2028-06", status: "upcoming",
      nfts: [
        {
          id: "plant-ashwagandha",
          name: "Ashwagandha",
          nameEs: "Ashwagandha — Fuerza del Caballo",
          description: "Withania somnifera — the strength of the horse. Ayurvedic king of adaptogens. Reduces cortisol, strengthens the nervous system.",
          emoji: "🐎",
          rarityTier: "standard",
          attributes: { origin: "India / Norte de África", type: "Adaptógeno rey", compounds: "Withanólidos", tradition: "Ayurveda" },
          promptHints: ["ashwagandha botanical horse strength art", "withania somnifera ayurvedic plant", "adaptogen roots orange berries", "ashwagandha ayurveda sacred india"],
        },
        {
          id: "plant-tulsi",
          name: "Tulsi",
          nameEs: "Tulsi — La Reina de las Hierbas",
          description: "Ocimum tenuiflorum — Holy Basil, the queen of herbs. Sacred to Vishnu, present in every Hindu household. Supreme adaptogen.",
          emoji: "👸",
          rarityTier: "standard",
          attributes: { origin: "India", type: "Planta sagrada adaptógena", compounds: "Eugenol + Ursólico", tradition: "Hinduismo / Ayurveda" },
          promptHints: ["tulsi holy basil sacred hindu art", "ocimum tenuiflorum deity plant", "queen herbs golden temple plant", "tulsi vishnu sacred botanical"],
        },
        {
          id: "plant-rhodiola",
          name: "Rhodiola",
          nameEs: "Rhodiola — La Raíz de Oro Ártica",
          description: "Rhodiola rosea — the arctic golden root. Viking adaptogen, used for extreme conditions. Anti-fatigue, cognitive clarity.",
          emoji: "❄️",
          rarityTier: "standard",
          attributes: { origin: "Ártico / Siberia / Escandinavia", type: "Adaptógeno extremo", compounds: "Rosavinas + Salidrosida", tradition: "Vikinga / Siberiana" },
          promptHints: ["rhodiola rosea arctic golden root art", "viking adaptogen tundra plant", "rhodiola mountain icy botanical", "golden root arctic resilience"],
        },
        {
          id: "plant-mucuna",
          name: "Mucuna Pruriens",
          nameEs: "Mucuna — La Vaina del Veludo",
          description: "Mucuna pruriens — the velvet bean. Ayurvedic treasure, natural L-DOPA source. Dopamine precursor, sexual vitality, lucid dreams.",
          emoji: "🫘",
          rarityTier: "standard",
          attributes: { origin: "Trópicos globales", type: "Planta nootrópica", compounds: "L-DOPA (Levodopa)", tradition: "Ayurveda / Africana" },
          promptHints: ["mucuna pruriens velvet bean botanical", "dopamine plant purple flowers vines", "tropical ayurvedic dopamine plant", "mucuna beans lustrous purple"],
        },
        {
          id: "plant-maca",
          name: "Maca",
          nameEs: "Maca — La Raíz de los Incas",
          description: "Lepidium meyenii — root of the Incas. Grown above 4,000m in the Andes. Stamina, fertility, hormonal balance since pre-Inca times.",
          emoji: "⛰️",
          rarityTier: "standard",
          attributes: { origin: "Altiplano Andino (Perú)", type: "Superalimento adaptógeno", compounds: "Macamidas + Macaenos", tradition: "Andina / Inca" },
          promptHints: ["maca root inca sacred andes art", "lepidium meyenii high altitude plant", "inca superroot cream yellow botanical", "maca mountain vitality andes"],
        },
        {
          id: "plant-chaga",
          name: "Chaga",
          nameEs: "Chaga — El Rey de los Hongos",
          description: "Inonotus obliquus — king of mushrooms. Siberian immune protector. Found on birch trees, used for millennia in northern shamanism.",
          emoji: "🍂",
          rarityTier: "rare",
          attributes: { origin: "Siberia / Norte de Europa / Canadá", type: "Hongo medicinal adaptógeno", compounds: "Beta-glucanos + Betulinato", tradition: "Siberiana / Nativa americana" },
          promptHints: ["chaga mushroom birch tree sacred", "inonotus obliquus siberian king fungus", "dark mushroom golden interior art", "chaga forest king mushroom mystic"],
        },
      ],
    },
  ],
};
